name: AutoBuild
permissions:
  contents: write
on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Create ZIP
      run: |
        cd target/x86_64-pc-windows-msvc/release
        7z a fast-cf.zip fast-cf.exe ../../../cloudflare_ipv4.txt
    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: target/x86_64-pc-windows-msvc/release/fast-cf.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
