name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: true
        tags: golangboyme/fast-cloudflare
